name: FaceSafety
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libcxx=20.1.8
  - libcxxabi=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.3
      - easydict==1.13
      - fastapi==0.127.0
      - filelock==3.20.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - grpcio==1.76.0
      - h11==0.16.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - insightface==0.7.3
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lz4==4.4.5
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - mtcnn==1.0.0
      - networkx==3.6.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - onnx==1.20.0
      - onnxruntime-gpu==1.23.2
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - prettytable==3.17.0
      - protobuf==6.33.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pymilvus==2.6.5
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - simsimd==6.5.12
      - six==1.17.0
      - starlette==0.50.0
      - stringzilla==4.5.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.12.20
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - triton==3.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wcwidth==0.2.14
